# Docker Compose configuration for Plex Meta Manager - Library automation

version: '3.9'
services:
    plex-meta-manager:
        command: '--run'
        image: kometateam/kometa
        volumes:
          - /mnt/user/appdata/plex-meta-manager/config:/config:rw
        container_name: plex-meta-manager