# Docker Compose configuration for AirCast - AirPlay to Chromecast bridge

version: '3.3'
services:
    airconnect:
        network_mode: host
        image: 1activegeek/airconnect
        restart: unless-stopped