# Docker Compose configuration for Appwrite - Backend-as-a-Service platform

services:
  # Appwrite - Backend-as-a-Service platform
  appwrite:
    container_name: appwrite
    hostname: appwrite_host
    restart: unless-stopped
    volumes:
      - '/home/jbpixel/Docker/appwrite/appwrite:/usr/src/code/appwrite:rw'
    image: 'appwrite/appwrite:0.15.1'
