# Docker Compose configuration for Minecraft Forge - Modded server

version: "3.3"
services:
  # Minecraftforge - Docker service
  minecraftforge:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraftforge_host
    ports:
      - 192.168.1.121:25567:25567/tcp
      - 192.168.1.121:25567:25567/udp

    volumes:
      - "/mnt/user/appdata/minecraftforge:/data"
    tty: true
    stdin_open: true
    environment:
      UID: 99
      GUID: 100
      TYPE: FORGE
      FORGE_VERSION: 43.2.0
      MAX_TICK_TIME: -1
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      LEVEL: "Cobbleworld"
      AUTOPAUSE_TIMEOUT_EST: "400"
      VERSION: 1.19.2
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 18
      MAX_WORLD_SIZE: 300000
      USE_AIKAR_FLAGS: "TRUE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 16
      OPS: user
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 1
      MODE: survival
      MOTD: "§c§lFeliz Jueves!"
      MAX_MEMORY: 10G
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 6
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 4G

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s