# Docker Compose configuration for Tailscale - Mesh VPN

version: "2.4"
services:
  # Tailscale - Managed mesh VPN
  tailscale:
      privileged: true
      hostname: tailscale                                          # This will become the tailscale device name
      network_mode: "host"
      container_name: tailscale
      image: tailscale/tailscale:latest
      volumes:
          - "/home/jbpixel/Docker/tailscale:/var/lib"        # State data will be stored in this directory
          - "/dev/net/tun:/dev/net/tun"                      # Required for tailscale to work
      cap_add:                                               # Required for tailscale to work
        - net_admin
        - sys_module
      command: tailscaled
      restart: unless-stopped